language: bash
services:
  - docker
deploy:
  provider: script
  script: make dockerpush
  on:
    branches:
      - master
      - develop
      - feature/dockerized-app
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always