language: bash
services:
  - docker
deploy:
  provider: script
  edge:
    branch: v2.0.5-beta
  script: make dockerpush
  on:
    branch: feature/dockerized-app-1
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always