jobs:
  include:
    - stage: my-family-ws-maven-install
      language: java
      jdk: openjdk22
      cache:
        directories:
          - "$HOME/.m2"
      install:
        - java --version
        - mvn clean install -P dev -f ./server/my-family-ws/pom.xml -DskipTests -Dmaven.test.skip=true
    - stage: my-family-ws-docker-deploy
      language: bash
      services:
        - docker
      deploy:
        - provider: script
          edge:
            branch: v2.0.3-beta.4
          script: make dockerpush DOCKER_IMAGE_NAME=my-family-ws DOCKER_IMAGE_SRC_DIR=server/my-family-ws
          on:
            branch: feature/dockerized-app-1
            #branches:
              #only:
                #- feature/dockerized-app-1
                #- develop
                #- master
        - provider: script
          edge:
            branch: v2.0.3-beta.4
          script: make dockerpush DOCKER_IMAGE_NAME=my-family-web DOCKER_IMAGE_SRC_DIR=client/my-family-app
          on:
            branch: feature/dockerized-app-1
            #branches:
              #only:
                #- feature/dockerized-app-1
                #- develop
                #- master
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - adishtimalsina11@gmail.com
      - dannyaqa.io@gmail.com
      - stellachoi120701@gmail.com
    on_success: always
    on_failure: always