jobs:
  include:
    - language: java
      jdk: openjdk22
      cache:
        directories:
          - "$HOME/.m2"
      install:
        - java --version
        - mvn clean install -P dev -f ./server/my-family-ws/pom.xml -DskipTests
    - language: bash
      services:
        - docker
      deploy:
        provider: script
        edge:
          branch: v2.0.3-beta.4
        script: make dockerpush DOCKER_IMAGE_NAME=my-family-web DOCKER_IMAGE_SRC_DIR=client/my-family-app
    - language: bash
      services:
        - docker
      deploy:
        provider: script
        edge:
          branch: v2.0.3-beta.4
        script: make dockerpush DOCKER_IMAGE_NAME=my-family-web
        on:
          branches:
            only:
              - feature/dockerized-app-1
              - develop
              - master
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - adishtimalsina11@gmail.com
      - dannyaqa.io@gmail.com
      - stellachoi120701@gmail.com
    on_success: always
    on_failure: always