language: bash
sudo: required
services:
- docker
deploy:
  - edge:
      branch: v2.0.5-beta
  - provider: script
    skip_cleanup: true
    script:
      - make dockerpush
  - on:
      branch: feature/dockerize-apps
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always