language: bash
sudo: required
services:
  docker
deploy:
  provider: script
  cleanup: false
  script:
    make dockerpush
  on:
    all_branches: true
notifications:
  email:
    recipients:
      tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always