language: bash
services:
  - docker
deploy:
  provider: script
  edge:
    branch: v2.0.3-beta.4
  script: make dockerpush
  on:
    branch: feature/dockerized-app-1
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - adishtimalsina11@gmail.com
      - dannyaqa.io@gmail.com
      - stellachoi120701@gmail.com
    on_success: always
    on_failure: always