language: bash
services:
  - docker
install:
  gem install ruby -v 2.7
  gem install json_pure -v 2.7.6
deploy:
  provider: script
  script: make dockerpush
  on:
    branch: feature/dockerized-app-1
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always