language: bash
sudo: required
services:
- docker
deploy:
  - edge:
      branch: true
  - provider: script
    skip_cleanup: true
    script:
      - make dockerpush
  - on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|deploy|feature/dockerize-apps)$
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always