language: bash
services:
  - docker
deploy:
  provider: script
  script: make dockerpush
  on:
    all_branches: true
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always