dist: jammy
jobs:
  include:
    - stage: my-family-app-angular-build
      language: node_js
      addons:
        apt:
          packages:
            - lftp
      node_js:
        - "20"
      cache:
        directories:
          - "client/my-family-app/node_modules"
      before_install:
        - cd client/my-family-app/
      install:
        - npm install
      script:
        - if [ $TRAVIS_BRANCH = "master" ]; then
          echo -e "Running npm run build --configuration production";
          npm run build -- --configuration production;
          else
          echo -e "Running npm run build --configuration development";
          npm run build -- --configuration development;
          fi;
    - stage: my-family-app-docker-deploy
      language: bash
      services:
        - docker
      script:
        - if [ "$TRAVIS_BRANCH" = "feature/dockerized-app-1" ] && [ "$TRAVIS_PULL_REQUEST" = "false"]; then
          make dockerpush DOCKER_IMAGE_NAME=my-family-web DOCKER_IMAGE_SRC_DIR=client/my-family-app
          fi
      #deploy:
        #- provider: script
          #edge:
            #branch: v2.0.3-beta.4
          #script: make dockerpush DOCKER_IMAGE_NAME=my-family-web DOCKER_IMAGE_SRC_DIR=client/my-family-app
          #on:
            #branches:
              #only:
                #- feature/dockerized-app-1
                #- develop
                #- master
    - stage: my-family-ws-maven-install
      language: java
      jdk: openjdk22
      cache:
        directories:
          - "$HOME/.m2"
      install:
        - java --version
        - mvn clean install -P dev -f ./server/my-family-ws/pom.xml -DskipTests -Dmaven.test.skip=true
    - stage: my-family-ws-docker-deploy
      language: bash
      services:
        - docker
      script:
        - if [ "$TRAVIS_BRANCH" = "feature/dockerized-app-1" ] && [ "$TRAVIS_PULL_REQUEST" = "false"]; then
          make dockerpush DOCKER_IMAGE_NAME=my-family-ws DOCKER_IMAGE_SRC_DIR=server/my-family-ws
          fi
      #deploy:
        #- provider: script
          #edge:
            #branch: v2.0.3-beta.4
          #script: make dockerpush DOCKER_IMAGE_NAME=my-family-ws DOCKER_IMAGE_SRC_DIR=server/my-family-ws
          #on:
            #branches:
              #only:
                #- feature/dockerized-app-1
                #- develop
                #- master
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
      - adishtimalsina11@gmail.com
      - dannyaqa.io@gmail.com
      - stellachoi120701@gmail.com
    on_success: always
    on_failure: always