language: bash
sudo: required
services:
  - docker
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - make dockerpush
  - on:
      branches:
        - master
        - develop
        - feature/dockerize-app
notifications:
  email:
    recipients:
      - tonte.pouncil@bytepushers.software
    on_success: always
    on_failure: always