export const errorMessagesMap: { [key: string]: string } = {
  'E001': 'User already exists',
  'E002': 'User not found',
  'E003': 'Invalid username or password',
  'E004': 'Unauthorized access. Please log in to continue',
  'E005': 'Access denied. You do not have permission to perform this action',
  'E006': 'Session expired. Please log in again',
  'E007': 'Required field is missing. Please fill out all required fields',
  'E008': 'Invalid data provided. Please check your input',
  'E009': 'Email format is incorrect. Please enter a valid email address',
  'E010': 'Password must be at least 8 characters long',
  'E011': 'Passwords do not match',
  'E012': 'Phone number format is invalid',
  'E013': 'Invalid date format. Please use the correct format (e.g., MM/DD/YYYY)',
  'E014': 'Failed to connect to the server. Please try again later',
  'E015': 'Network timeout. Please check your internet connection',
  'E016': 'An unexpected error occurred. Please refresh the page and try again',
  'E017': 'Service is currently unavailable. Please try again later',
  'E018': 'The requested resource was not found',
  'E019': 'Payment failed. Please check your payment details and try again',
  'E020': 'Insufficient funds. Please add funds or use a different payment method',
  'E021': 'Transaction limit exceeded. Please contact support',
  'E022': 'Invalid payment method. Please choose a valid method',
  'E023': 'Payment gateway is currently unavailable. Please try again later',
  'E024': 'File upload failed. Please try again',
  'E025': 'File size exceeds the maximum limit. Please upload a smaller file',
  'E026': 'Invalid file type. Please upload a valid file (e.g., PDF, PNG, JPG)',
  'E027': 'File is corrupted. Please upload a valid file',
  'E028': 'Data conflict. The record you are trying to save already exists',
  'E029': 'Data not found. The requested information does not exist',
  'E030': 'Database connection error. Please try again later',
  'E031': 'Data integrity error. Please contact support for assistance',
  'E032': 'Too many requests. Please wait a moment and try again',
  'E033': 'You have exceeded the rate limit. Please slow down',
  'E034': 'Failed to send email. Please try again',
  'E035': 'Email address not verified. Please check your inbox',
  'E036': 'Notification service is currently unavailable',
  'E037': 'An unknown error occurred. Please try again later',
  'E038': 'Operation failed. Please contact support',
  'E039': 'Invalid request. Please check your input and try again',
  'E040': 'Account already exists with this email',
  'E041': 'Account is locked. Please reset your password or contact support',
  'E042': 'Account is disabled. Please contact support for further assistance',
  'E043': 'Profile update failed. Please check your input and try again',
};
