services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/myfamily?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=myfamily
      - SPRING_DATASOURCE_PASSWORD=myfamily
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=myfamily
      - MYSQL_USER=myfamilyuser
      - MYSQL_PASSWORD=myfamilypass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql-data: