services:
  springboot-app:
    container_name: my-family-ws
    image: my-family-ws:latest
    restart: always
    build: .
    ports:
      - 8090:8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/myfamily?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: myfamily
      SPRING_DATASOURCE__PASSWORD: myfamily
    depends_on:
      - mysqldb
      #volumes:
      #- springboot-app:/var/app
      #networks:
      #- bp-network

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myfamily
      MYSQL_USER: myfamily
      MYSQL_PASSWORD: myfamily
    volumes:
      - mysql-data:/var/lib/mysql
#      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
      #networks:
      #- bp-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  mysql-data:

  #networks:
  #bp-network: