services:
  my-family-app:
    container_name: my-family-angular-app-container
    build: .
    image: tontepouncil/my-family-web:latest
    ports:
      - 4100:4100
    expose:
      - 4100
    networks:
      - bp-internal-network
networks:
  bp-internal-network:
    driver: bridge
