# default ${project-dir}/src/main/docker/Dockerfile for io.fabric8.docker-maven-plugin as plugin default
# location is ${project-dir}/src/main/docker.
# However io.fabric8.docker-maven-plugin has been configured to use the ${project-dir}/Dockerfile instead.